<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('patients', function (Blueprint $table) {
            $table->id();
            
            // Core Identifiers (Unique Patient ID is generated by the application)
            $table->string('patient_id')->unique()->comment('System generated unique patient file number');
            $table->string('national_id')->nullable()->unique()->index()->comment('National Identification Number (optional)');
            
            // Demographic Data
            $table->string('name');
            $table->integer('age')->nullable();
            $table->enum('gender', ['Male', 'Female', 'Other']);
            $table->text('address')->nullable();
            
            // Contact & Kin
            $table->string('phone')->unique()->index();
            $table->string('next_of_kin')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('patients');
    }
};
